esphome:
  name: louder-esp32
  friendly_name: louder-esp32
  min_version: 2024.12.4
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
  # use priority 250 so gpio and i2c dac is setup before volume is set
    priority: 250
    then:
    # Set a volume limit just to be safe...
    - media_player.volume_set:
        id: louder_mediaplayer
        volume: 5%
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"
      CONFIG_ESP32_S3_BOX_BOARD: "y"
      CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY: "y"

      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"

      # Settings based on https://github.com/espressif/esp-adf/issues/297#issuecomment-783811702
      CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM: "16"
      CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM: "512"
      CONFIG_ESP32_WIFI_STATIC_TX_BUFFER: "y"
      CONFIG_ESP32_WIFI_TX_BUFFER_TYPE: "0"
      CONFIG_ESP32_WIFI_STATIC_TX_BUFFER_NUM: "8"
      CONFIG_ESP32_WIFI_CACHE_TX_BUFFER_NUM: "32"
      CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED: "y"
      CONFIG_ESP32_WIFI_TX_BA_WIN: "16"
      CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED: "y"
      CONFIG_ESP32_WIFI_RX_BA_WIN: "32"
      CONFIG_LWIP_MAX_ACTIVE_TCP: "16"
      CONFIG_LWIP_MAX_LISTENING_TCP: "16"
      CONFIG_TCP_MAXRTX: "12"
      CONFIG_TCP_SYNMAXRTX: "6"
      CONFIG_TCP_MSS: "1436"
      CONFIG_TCP_MSL: "60000"
      CONFIG_TCP_SND_BUF_DEFAULT: "65535"
      CONFIG_TCP_WND_DEFAULT: "65535"  # Adjusted from linked settings to avoid compilation error
      CONFIG_TCP_RECVMBOX_SIZE: "512"
      CONFIG_TCP_QUEUE_OOSEQ: "y"
      CONFIG_TCP_OVERSIZE_MSS: "y"
      CONFIG_LWIP_WND_SCALE: "y"
      CONFIG_TCP_RCV_SCALE: "3"
      CONFIG_LWIP_TCPIP_RECVMBOX_SIZE: "512"

      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"

      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"  # TLS1.3 support isn't enabled by default in IDF 5.1.5
# Enable logging
logger:


# Enable Home Assistant API
api:
  encryption:
    key: !secret louder_api

ota:
  - platform: esphome
    password: !secret louder_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

psram:
  mode: octal
  speed: 80MHz

external_components:
  - source:
      type: git
      url: https://github.com/gnumpi/esphome_audio
      ref: main
    components: [ adf_pipeline, i2s_audio ]
    refresh: 0s

  - source: github://mrtoy-me/esphome-components-test@main
    components: [ tas5805m ]
    refresh: 0s

i2c:
  - id: internal_i2c
    sda: GPIO8
    scl: GPIO9
    frequency: 400kHz
    scan: True

audio_dac:
  - platform: tas5805m
    id: tas5805_dac
    i2c_id: internal_i2c
    enable_pin: GPIO17

i2s_audio:
  - id: i2s_out
    i2s_lrclk_pin: GPIO15
    i2s_bclk_pin: GPIO14

adf_pipeline:
  - platform: i2s_audio
    type: audio_out
    id: adf_i2s_out
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO16

media_player:
  - platform: adf_pipeline
    id: louder_mediaplayer
    name: Louder-ESP32 mediaplayer
    keep_pipeline_alive: false
    internal: false
    pipeline:
      - self
      - adf_i2s_out
    on_play:
      - switch.turn_on: enable_louder

switch:
  - platform: template
    name: Enable Louder-ESP32
    id: enable_louder
    optimistic: true
    turn_on_action:
      - lambda: !lambda |-
          id(tas5805_dac).set_deep_sleep_off();
    turn_off_action:
      - lambda: !lambda |-
          id(tas5805_dac).set_deep_sleep_on();

  - platform: template
    name: Mute Louder-ESP32
    optimistic: true
    turn_on_action:
      - lambda: !lambda |-
          id(tas5805_dac).set_mute_on();
    turn_off_action:
      - lambda: !lambda |-
          id(tas5805_dac).set_mute_off();

binary_sensor:
  - platform: template
    name: Louder-ESP32 Is Muted
    lambda: |-
      return id(tas5805_dac).is_muted();